# Default values for flowmill-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Check with Flowmill for guidance on expected resource usage, if you would like to set limits.

# Follow the "Settings/Deployment" tab of your UI to get the values below
# 
auth:
  keyId: ""
  keySecret: ""


  # If your agent keys are already stored in a k8s secret, 
  # uncomment below and update the k8s secret name
  #existingSecret: "YOUR_K8S_SECRET_NAME"

  # If using segment.io's chamber (https://github.com/segmentio/chamber) to store agent keys,
  # uncomment below and update the chamber service name for which secrets were stored.
  # Agent keys must be stored using secret keys `FLOWMILL_AUTH_KEY_ID` and `FLOWMILL_AUTH_SECRET`.
  # chamberService: "YOUR_CHAMBER_SERVICE"

flowmill:
  clusterName: TODO_CHOOSE_YOUR_CLUSTER_NAME_HERE
  version: latest-v0.9
  services:
    host: app.flowmill.com
  intake:
    host: intake.flowmill.com
    #
    # nameOverride:

images:
  repository: gcr.io/flowmill-gcr
  pullPolicy: Always

log:
  console: false
  # possible values: { error | warning | info | debug | trace }
  # NOTE: debug and trace are only available in debug builds
  level: warning

# Enable to use a proxy to connect to Flowmill intake and services
# NOTE: only HTTP proxies are currently supported
# NOTE: don't specify the protocol scheme (e.g.: http://), just the hostname/address
proxy:
  enabled: false
  #host: myproxy.com
  #port: 1080

# Configuration for Flowmill's kernel collector
agent:
  imageName: agent
  nodeSelector: {}
  httpMetrics:
    disabled: false

  tolerations:
  - operator: "Exists"
    effect: "NoExecute"
  - operator: "Exists"
    effect: "NoSchedule"

  affinity: {}
  resources: {}

  # uncomment the line below to disable automatic kernel headers fetching
  #fetchKernelHeaders: false

  cpuMemIo:
    # Set this to false to disable CPU/Mem/IO collection
    enabled: false
  #  # minimum micro batch size for CPU/Mem/IO polling (comment for default value)
  #  #minBatch: 1
  #  # maximum micro batch size for CPU/Mem/IO polling (comment for default value)
  #  #maxBatch: 5
  #  # maximum time budget (us) per CPU/Mem/IO micro batch (comment for default value)
  #  #pollBudgetUs: 5
  #  # poll count between CPU/Mem/IO micro batches (comment for default value)
  #  #cooldown: 3

  # assumes docker is being used for kubernetes containers
  useDockerMetadata: true
  # Set `dumpDockerMetadata` to dump the container metadata retrieved from
  # docker engine into the agent's pod under `/var/run/flowmill/dump`.
  #
  # The metadata can be retrieved using the command:
  # ```
  # kubectl -n flowmill cp AGENT_POD_NAME:/var/run/flowmill/dump DEST_DIR
  # ```
  #dumpDockerMetadata: true

  # uncomment to enable enrichment using Nomad metadata (https://www.nomadproject.io/)
  #collectNomadMetadata: true

# Configuration for Flowmill's AWS collector.
awsCollector:
  enabled: false
  imageName: aws-collector


# Configuration for Flowmill's Kubernetes collector
k8sCollector:
  enabled: true
  relay:
    imageName: k8s-relay
  watcher:
    imageName: k8s-watcher


rbac:
  create: true

podSecurityPolicy:
  enabled: true
  annotations: {}
    ## Specify pod annotations
    ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#apparmor
    ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp
    ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#sysctl
    ##
    # seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    # seccomp.security.alpha.kubernetes.io/defaultProfileName: 'docker/default'
    # apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'
