# Default values for flowmill-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Check with Flowmill for guidance on expected resource usage, if you would like to set limits.
agent:
  repository: 966881513036.dkr.ecr.us-east-1.amazonaws.com/flowmill/flowmill-agent
  tag: cf-v0.7.14-313-g78637843-1562093427825
  pullPolicy: IfNotPresent
  resources: {}
relay:
  repository: 966881513036.dkr.ecr.us-east-1.amazonaws.com/flowmill/flowmill-k8s-relay
  tag: v0.7.14-139-g3b1e2590
  pullPolicy: IfNotPresent
  resources: {}
watcher:
  repository: 966881513036.dkr.ecr.us-east-1.amazonaws.com/flowmill/flowmill-k8s-watcher
  tag: 0.7.12
  pullPolicy: IfNotPresent
  resources: {}

nodeSelector: {}

tolerations:
- operator: "Exists"
  effect: "NoExecute"
- operator: "Exists"
  effect: "NoSchedule"

flowmill:
  clusterName: my-kubernetes-cluster

  # You can either set this to the name of an existing secret if one is already deployed...
  # or place auth.yaml in ./static/auth.yaml
  authYamlExistingSecret: null

affinity: {}

agentArgs:
  - --auth-config
  - /etc/flowmill/auth.yaml
  - --config-file
  - /etc/flowmill/config.yaml
  - --enable-http-metrics

rbac:
  create: true

podSecurityPolicy:
  enabled: false
  annotations: {}
    ## Specify pod annotations
    ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#apparmor
    ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp
    ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#sysctl
    ##
    # seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    # seccomp.security.alpha.kubernetes.io/defaultProfileName: 'docker/default'
    # apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'
