# Default values for flowmill-agent-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: 966881513036.dkr.ecr.us-east-1.amazonaws.com/flowmill/flowmill-agent
  tag: latest
  pullPolicy: Always

agentConfig:
  # This is passed along in the agent's config.yaml as the "environment" tag.
  # It doesn't HAVE to match your cluster name.
  clusterName: k8s

# Check with Flowmill for guidance on expected resource usage, if you would like to set limits.
agent:
  resources: {}
collector:
  resources: {}

nodeSelector: {}

tolerations:
- operator: "Exists"
  effect: "NoExecute"
- operator: "Exists"
  effect: "NoSchedule"

flowmill:
  clusterName: my-kubernetes-cluster

  # Set this to the name of an existing secret if this is already deployed
  # authYamlExistingSecret:

  authYaml:
    dst: MISSING
    port: MISSING
    key: |
      -----BEGIN PRIVATE KEY-----
      ....
      -----END PRIVATE KEY-----
    crt: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    auth: MISSING
    apikey: MISSING
    tenant: MISSING

affinity: {}

rbac:
  create: true
