# Default values for flowmill-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Check with Flowmill for guidance on expected resource usage, if you would like to set limits.
agent:
  repository: 966881513036.dkr.ecr.us-east-1.amazonaws.com/flowmill/flowmill-agent
  tag: 0.7.5
  pullPolicy: Always
  resources: {}
relay:
  repository: 966881513036.dkr.ecr.us-east-1.amazonaws.com/flowmill/flowmill-k8s-relay
  tag: 0.7.5
  pullPolicy: Always
  resources: {}
watcher:
  repository: 966881513036.dkr.ecr.us-east-1.amazonaws.com/flowmill/flowmill-k8s-watcher
  tag: 0.7.5
  pullPolicy: Always
  resources: {}

nodeSelector: {}

tolerations:
- operator: "Exists"
  effect: "NoExecute"
- operator: "Exists"
  effect: "NoSchedule"

flowmill:
  clusterName: my-kubernetes-cluster

  # You can either set this to the name of an existing secret if one is already deployed...
  authYamlExistingSecret: null

  # ... or you can add auth.yaml contents to .flowmill.authYaml
  authYaml:
    dst: MISSING
    port: MISSING
    key: |
      -----BEGIN PRIVATE KEY-----
      ....
      -----END PRIVATE KEY-----
    crt: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    auth: MISSING
    apikey: MISSING
    tenant: MISSING

affinity: {}

rbac:
  create: true
