{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ include "flowmill-agent-k8s.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ include "flowmill-agent-k8s.fullname" . }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - {{ include "flowmill-agent-k8s.fullname" . }}
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{- end -}}
