{{- if not .Values.auth.existingSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "flowmill.fullname" . }}-agent-key
  labels:
    app: "{{ template "flowmill.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
stringData:
  flowmill_agent_key_id: {{ .Values.auth.keyId }}
  flowmill_agent_secret: {{ .Values.auth.keySecret }}
{{- end }}
