{{- if not .Values.flowmill.agentExistingSecret }}
{{- if hasKey .Values.flowmill "agent" }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "flowmill-k8s.fullname" . }}-agent-key
  labels:
    app: "{{ template "flowmill-k8s.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  flowmill_agent_key_id: {{ .Values.flowmill.agent.keyId | b64enc }}
  flowmill_agent_secret: {{ .Values.flowmill.agent.secret | b64enc }}
{{- end }}
{{- end }}
