{{- if not .Values.flowmill.authYamlExistingSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "flowmill-k8s.fullname" . }}-auth
  labels:
    app: "{{ template "flowmill-k8s.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
stringData:
{{ toYaml .Values.flowmill.authYaml | indent 4 }}

{{- end }}
